name: Nightly Grype Security Scan

on:
  schedule:
    # Run at midnight UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  grype_scan:
    uses: ./.github/workflows/grype_scan_reusable.yaml
    with:
      slack_webhook_secret: 'SLACK_TESTS_WEBHOOK_URL'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TESTS_WEBHOOK_URL }}
